src/Entity/Artwork.php
<?php

namespace App\Entity;

use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\ArtworkRepository;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ArtworkRepository::class)]
#[Vich\Uploadable]
class Artwork
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank()]
    #[Assert\Length(max: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank()]
    #[Assert\Length(max: 255)]
    private ?string $tool = null;

    #[ORM\Column]
    #[Assert\NotBlank()]
    #[Assert\Regex('/[\d]{1,}\w+/')]
    #[Assert\Positive]
    private ?int $height = null;

    #[ORM\Column]
    #[Assert\NotBlank()]
    #[Assert\Regex('/[\d]{1,}\w+/')]
    #[Assert\Positive]
    private ?int $width = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank()]
    #[Assert\Length(max: 255)]
    private ?string $base = null;

    #[ORM\Column]
    #[Assert\NotBlank()]
    #[Assert\Positive]
    private ?int $work_duration = null;

    #[ORM\ManyToOne(inversedBy: 'artworks')]
    private ?Artist $artist = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $artwork = null;

    #[Assert\File(
        maxSize: '2M',
        mimeTypes: ['image/jpeg', 'image/png', 'image/webp'],
        )]
    #[Vich\UploadableField(mapping: 'artwork_file', fileNameProperty: 'artwork')]
    private ?File $artworkFile = null;

    #[ORM\Column(nullable: true)]
    private ?DateTimeImmutable $updatedAt = null;

    #[ORM\ManyToOne(inversedBy: 'artworks')]
    private ?Category $category = null;
 
    #[ORM\ManyToMany(targetEntity: Artist::class, mappedBy: 'favory')]
    private Collection $artists;

    #[ORM\OneToMany(mappedBy: 'artwork', targetEntity: Comment::class)]
    private Collection $comments;


    public function __construct()
    {
        $this->artists = new ArrayCollection();
        $this->comments = new ArrayCollection();

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getTool(): ?string
    {
        return $this->tool;
    }

    public function setTool(string $tool): self
    {
        $this->tool = $tool;

        return $this;
    }

    public function getHeight(): ?int
    {
        return $this->height;
    }

    public function setHeight(int $height): self
    {
        $this->height = $height;

        return $this;
    }

    public function getWidth(): ?int
    {
        return $this->width;
    }

    public function setWidth(int $width): self
    {
        $this->width = $width;

        return $this;
    }

    public function getBase(): ?string
    {
        return $this->base;
    }

    public function setBase(string $base): self
    {
        $this->base = $base;

        return $this;
    }

    public function getWorkDuration(): ?int
    {
        return $this->work_duration;
    }

    public function setWorkDuration(int $work_duration): self
    {
        $this->work_duration = $work_duration;

        return $this;
    }

    public function getArtist(): ?Artist
    {
        return $this->artist;
    }

    public function setArtist(?Artist $artist): self
    {
        $this->artist = $artist;

        return $this;
    }

     public function getArtwork(): ?string
    {
        return $this->artwork;
    }

    public function setArtwork(?string $artwork): self
    {
        $this->artwork = $artwork;

        return $this;
    }

    public function getArtworkFile(): ?File
    {
        return $this->artworkFile;
    }

    public function setArtworkFile(?File $image = null): self
    {
        $this->artworkFile = $image;

        if ($image) {
            $this->updatedAt = new DateTimeImmutable();
        }
        return $this;
    }

    public function getUpdatedAt(): ?DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection<int, Artist>
     */
    public function getArtists(): Collection
    {
        return $this->artists;
    }

    public function addArtist(Artist $artist): self
    {
        if (!$this->artists->contains($artist)) {
            $this->artists->add($artist);
            $artist->addFavory($this);
        }

        return $this;
    }

    public function removeArtist(Artist $artist): self
    {
        if ($this->artists->removeElement($artist)) {
            $artist->removeFavory($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setArtwork($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getArtwork() === $this) {
                $comment->setArtwork(null);
            }
        }

        return $this;
    }



}

src/Form/ArtworkType.php
<?php

namespace App\Form;

use App\Entity\Artwork;
use App\Entity\Category;
use Doctrine\ORM\Mapping\Entity;
use Symfony\Component\Form\AbstractType;
use Vich\UploaderBundle\Form\Type\VichFileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;

class ArtworkType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'label' => 'Titre de l\'œuvre',
                'attr' => [
                    'class' => 'form-control my-2',
                ],
            ])
            ->add('tool', TextType::class, [
                'label' => 'Outil principal',
                'attr' => [
                    'class' => 'form-control my-2',
                ],
                ])
                ->add('base', TextType::class, [
                    'label' => 'Support',
                    'attr' => [
                        'class' => 'form-control my-2',
                    ],
                    ])
            ->add('height', NumberType::class, [
                'label' => 'Hauteur en cm',
                'attr' => [
                    'class' => 'form-control my-2',
                ],
            ])
            ->add('width', NumberType::class, [
                'label' => 'Largeur en cm',
                'attr' => [
                    'class' => 'form-control my-2',
                ],
            ])
            ->add('work_duration', NumberType::class, [
                'label' => 'Temps de travail en min',
                'attr' => [
                    'class' => 'form-control my-2',
                ],
            ])
            ->add('category', EntityType::class, [
                'class' => Category::class,
                'choice_label' => 'name',
                'label' => 'Catégories',
                'multiple' => false,
                'expanded' => false,
                'attr' => ['class' => 'form-select my-2 '],
                'by_reference' => true,
            ])
            ->add('artworkFile', VichFileType::class, [
                'label' => 'Charger une œuvre',
                'attr' => [
                    'class' => 'form-control',
                ],
                'label_attr' => [
                    'class' => "form-label my-2",
                ],
                'required'      => false,
                'allow_delete'  => false, // not mandatory, default is true
                'download_uri' => false, // not mandatory, default is true
                'download_label' => false,
            ]);;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Artwork::class,
        ]);
    }
}

src/Controller/ArtworkController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\Artwork;
use App\Form\ArtworkType;
use App\Repository\ArtistRepository;
use App\Repository\ArtworkRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/oeuvres', name: 'app_artwork_')]
class ArtworkController extends AbstractController
{
    #[Route('/', name: 'index')]
    public function index(): Response
    {
        return $this->render('artwork/index.html.twig', []);
    }

    #[Route('/favorites', name: 'favories')]
    public function favories(): Response
    {
        return $this->render('artwork/favories.html.twig', []);
    }

    #[Route('/ajouter', name: 'new', methods: ['GET', 'POST'])]
    public function new(Request $request, ArtworkRepository $artworkRepository): Response
    {
        /** @var User */
        $user = $this->getUser();

        $artwork = new Artwork();
        $form = $this->createForm(ArtworkType::class, $artwork);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $artwork->setArtist($user->getArtist());
            $artworkRepository->save($artwork, true);

            $this->addFlash('success', 'L\'œuvre a bien été ajoutée.');

            return $this->redirectToRoute('app_artwork_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('artwork/new.html.twig', [
            'artwork' => $artwork,
            'form' => $form,
        ]);
    }



    #[Route('/{id}/modifier', name: 'edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Artwork $artwork, ArtworkRepository $artworkRepository): Response
    {
        $form = $this->createForm(ArtworkType::class, $artwork);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $artworkRepository->save($artwork, true);

            $this->addFlash('success', 'L\'œuvre a bien été modifiée.');

            return $this->redirectToRoute('app_artwork_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('artwork/edit.html.twig', [
            'artwork' => $artwork,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'delete', methods: ['POST'])]
    public function delete(Request $request, Artwork $artwork, ArtworkRepository $artworkRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $artwork->getId(), $request->request->get('_token'))) {
            $artworkRepository->remove($artwork, true);
            $this->addFlash('success', 'L\'œuvre a bien été supprimée.');
        }

        return $this->redirectToRoute('app_artwork_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/ajouter-aux-favories/{id}', methods: ['GET', 'POST'], name: 'add_favory')]
    public function addToFavories(Artwork $artwork, ArtistRepository $artistRepository): Response
    {
        if (!$artwork) {
            $this->addFlash("danger", "Aucune œuvre correspondante trouvée.");
        }

        /** @var \App\Entity\User */
        $user = $this->getUser();
        $artist = $user->getArtist();

        if ($artist->isInFavorite($artwork)) {
            $artist->removeFavory($artwork);
        } else {
            $artist->addFavory($artwork);
        }

        $artistRepository->save($artist, true);

        return $this->json(['isInFavorite' => $artist->getFavory()->contains($artwork)]);
    }
}

templates/artwork/_delete_form.html.twig
<form method="post" action="{{ path('app_artwork_delete', {'id': artwork.id}) }}" onsubmit="return confirm('Veuillez confirmer la suppression.');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ artwork.id) }}">
    <button class=" mt-2 btn btn-sm btn-outline-danger d-flex"><i class="bi bi-eraser me-1"></i>Supprimer</button>
</form>

templates/artwork/_form.html.twig
{{ form_start(form) }}
{{ form_widget(form) }}
<div class="d-flex justify-content-between mt-4">
	<a class="btn btn-outline-primary" href="{{ path('app_artwork_index') }}">Retour</a>
	<button class="btn btn-primary">{{ button_label|default('Enregistrer') }}</button>
</div>

{{ form_end(form) }}

templates/artwork/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{ parent() ~ ' | Modification œuvre'}}
{% endblock %}
{% block stylesheets %}
	{{ parent() }}
{% endblock %}
{% block javascripts %}
	{{ parent() }}
	{{ encore_entry_script_tags('previewArtworkImage') }}
{% endblock %}
{% block content %}
	<div class="container min-vh-100">
		<div class="row d-flex justify-content-center">
			<h1 class="my-5 pt-5">Modification d'une œuvre</h1>
			<div class="d-sm-flex justify-content-between">
				<div class="col-sm-6">

					{{ include('artwork/_form.html.twig', {'button_label': 'Modifier'}) }}

				</div>

				<div class="col-sm-3 me-5 align-self-end ">
					<img class=" border h-100" src="{{ artwork.artwork is empty ? "https://picsum.photos/id/" ~ random(1, 200) ~ "/300/200" : vich_uploader_asset(artwork) }}" alt="Une œuvre" id="artworkImage">
				</div>
			</div>

		</div>
	</div>
{% endblock %}

templates/artwork/favories.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{ parent() ~ ' | Inspiration' }}
{% endblock %}

{% block stylesheets %}
	{{ parent() }}

{% endblock %}
{% block javascripts %}
	{{ parent() }}
	{{ encore_entry_script_tags('favorite') }}
{% endblock %}
{% block content %}

	<div class="container mt-5 min-vh-100	">
		<h2 class="font-subtitle display-5 my-5 pt-5 rounded-end">Inspirations favorites</h2>

		<div class="row">

			{% for artwork in app.user.artist.favory %}

				<div class="col-12 col-sm-6">
					<div class="card mb-3 .card-artwork">
						<div class="row g-0">
							<div class="col-md-8 position-relative">
								{% if is_granted('ROLE_ARTIST') %}
									<a class="toggleFavorite position-absolute top-0 start-0 ms-3 text-decoration-none text-tertiary" href="{{ path('app_artwork_add_favory', { id: artwork.id }) }}">
										<i class="bi fs-1 {{ app.user.artist.isInFavorite(artwork) ? 'bi-palette-fill' : 'bi-palette' }}"></i>
									</a>
								{% endif %}
								<a href="{{ path('app_inspiration_artwork', { 'id':artwork.id }) }}">
									<img src="{{ artwork.artwork is null ? "https://picsum.photos/id/" ~ random(1, 200) ~ "/300/200" : vich_uploader_asset(artwork) }}" class="img-fluid rounded-start card-artwork" alt="...">
								</a>
							</div>
							<div class="col-md-4">
								<div class="card-body">
									<h5 class="card-title">{{ artwork.name }}</h5>
									<p class="card-text">
										<small class="text-muted">{{ (artwork.workDuration / 60)|round(0, 'ceil') }}h</small>
									</p>
									<ul class="list-group list-group-flush">
										<li class="list-group-item">{{ artwork.artist.user.lastname}}</li>
										<li class="list-group-item">{{ artwork.tool}}</li>
										<li class="list-group-item">{{ artwork.height ~ 'x' ~ artwork.width}}</li>

									</ul>
								</div>
							</div>
						</div>
					</div>


				</div>
			{% else %}
				<tr>
					<td colspan="10">Aucunes œuvres en favoris actuellement</td>
				</tr>

			{% endfor %}
		</div>
		<div class="d-flex justify-content-end">
			<a class="btn btn-outline-primary" href="{{ path('app_index') }}">
				<i class="me-2 bi bi-arrow-left-square"></i>Retour</a>
		</div>
	</div>
{% endblock %}

templates/artwork/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	{{ parent() ~ '| Mes œuvres'}}
{% endblock %}

{% block content %}
	<div class="container min-vh-100">
		<div class="d-flex justify-content-between mt-5 pt-5">
			<h1 class="">Mes œuvres</h1>
			<a class="btn btn-dark h-100 align-content-center d-flex" href="{{ path('app_artwork_new') }}"><i class="bi bi-plus-square me-1"></i>Ajouter une œuvre</a>
		</div>
		<table class="table">
			<thead>

				<tr>
					<th class="w-auto">Nom de l'œuvre</th>
					<th class="w-auto">Outil</th>
					<th class="w-auto">Dimension</th>
					<th class="w-auto">Support</th>
					<th class="w-auto">Temps</th>
					<th class="w-auto">Image</th>
					<th class="w-auto"></th>
				</tr>
			</thead>
			<tbody>
				{% for artwork in app.user.artist.artworks %}
					<tr>
						<td>{{ artwork.name }}</td>
						<td>{{ artwork.tool }}</td>
						<td>{{ artwork.height ~ 'x' ~ artwork.width }}</td>
						<td>{{ artwork.base }}</td>
						<td>{{ (artwork.workDuration / 60)|round(0, 'ceil') }}h</td>
						<td>
							<img src="{{ artwork.artwork is null ? "https://picsum.photos/id/" ~ random(1, 200) ~ "/300/200" : vich_uploader_asset(artwork) }}" class="img-thumbnail w-25" alt="...">
						</td>

						<td class="">
							<a class="btn btn-sm btn-outline-primary ms-1" href="{{ path('app_artwork_edit', {'id': artwork.id}) }}"><i class="bi bi-brush me-1"></i>Modifier</a>

							{{ include('artwork/_delete_form.html.twig') }}
						</td>
					</tr>
				{% else %}
					<tr>
						<td colspan="10">Aucunes œuvres enegistrées</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
		<div class="d-flex justify-content-end">
		      <a class="btn btn-outline-primary d-flex" href="{{ path('app_index') }}"><i class="me-2 bi bi-arrow-left-square"></i>Retour</a>
		</div>

	</div>
{% endblock %}

templates/artwork/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}
{{ parent() ~ ' | Ajouter une œuvre'}}
{% endblock %}

{% block content %}
<div class="container">
   <div class="row mt-5 pt-5 justify-content-center">
    <h1 class="">Ajouter une œuvre</h1>
   <div class="col-12 col-sm-6">

    {{ include('artwork/_form.html.twig') }}

   </div>
   </div>
</div>
{% endblock %}