src/Entity/Artist.php
<?php

namespace App\Entity;

use App\Repository\ArtistRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ArtistRepository::class)]
class Artist
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $about_me = null;

    #[ORM\OneToMany(mappedBy: 'artist', targetEntity: Artwork::class)]
    private Collection $artworks;

    #[ORM\OneToOne(inversedBy: 'artist', cascade: ['persist', 'remove'])]
    private ?User $user = null;

    #[ORM\ManyToMany(targetEntity: Artwork::class, inversedBy: 'artists')]
    private Collection $favory;

    #[ORM\ManyToMany(targetEntity: self::class, inversedBy: 'follower')]
    private Collection $follow;

    #[ORM\ManyToMany(targetEntity: self::class, mappedBy: 'follow')]
    private Collection $follower;

    #[ORM\OneToMany(mappedBy: 'author', targetEntity: Comment::class)]
    private Collection $comments;



    public function __construct()
    {
        $this->artworks = new ArrayCollection();
        $this->favory = new ArrayCollection();
        $this->follow = new ArrayCollection();
        $this->follower = new ArrayCollection();
        $this->comments = new ArrayCollection();
  
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAboutMe(): ?string
    {
        return $this->about_me;
    }

    public function setAboutMe(?string $about_me): self
    {
        $this->about_me = $about_me;

        return $this;
    }

    /**
     * @return Collection<int, Artwork>
     */
    public function getArtworks(): Collection
    {
        return $this->artworks;
    }

    public function addArtwork(Artwork $artwork): self
    {
        if (!$this->artworks->contains($artwork)) {
            $this->artworks->add($artwork);
            $artwork->setArtist($this);
        }

        return $this;
    }

    public function removeArtwork(Artwork $artwork): self
    {
        if ($this->artworks->removeElement($artwork)) {
            // set the owning side to null (unless already changed)
            if ($artwork->getArtist() === $this) {
                $artwork->setArtist(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Artwork>
     */
    public function getFavory(): Collection
    {
        return $this->favory;
    }

    public function addFavory(Artwork $artwork): self
    {
        if (!$this->favory->contains($artwork)) {
            $this->favory->add($artwork);
        }

        return $this;
    }

    public function removeFavory(Artwork $artwork): self
    {
        $this->favory->removeElement($artwork);

        return $this;
    }

    public function isInFavorite(Artwork $artwork): bool
    {
        return $this->favory->contains($artwork);
    }

    /**
     * @return Collection<int, self>
     */
    public function getFollow(): Collection
    {
        return $this->follow;
    }

    public function addFollow(self $follow): self
    {
        if (!$this->follow->contains($follow)) {
            $this->follow->add($follow);
        }

        return $this;
    }

    public function removeFollow(self $follow): self
    {
        $this->follow->removeElement($follow);

        return $this;
    }

    /**
     * @return Collection<int, self>
     */
    public function getFollower(): Collection
    {
        return $this->follower;
    }
    
    public function isFollow(Artist $artist): bool
    {
        return $this->follow->contains($artist);
    }
    
    public function addFollower(self $follower): self
    {
        if (!$this->follower->contains($follower)) {
            $this->follower->add($follower);
            $follower->addFollow($this);
        }

        return $this;
    }

    public function removeFollower(self $follower): self
    {
        if ($this->follower->removeElement($follower)) {
            $follower->removeFollow($this);
        }

        return $this;
    }


    public function isFollower(Artist $artist): bool
    {
        return $this->follower->contains($artist);
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }

 



}

templates/component/_accordion.html.twig
<div class="accordion" id="accordionPanelsStayOpen_{{ artist.user.lastname }}">
	<div class="accordion-item">
		<h2 class="accordion-header" id="panelsStayOpen-headingOne_{{ artist.user.lastname }}">
			<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne_{{ artist.user.lastname }}" aria-expanded="false" aria-controls="panelsStayOpen-collapseOne_{{ artist.user.lastname }}">
				Extrait de ses œuvres
			</button>
		</h2>
		<div id="panelsStayOpen-collapseOne_{{ artist.user.lastname }}" class="accordion-collapse collapse " aria-labelledby="panelsStayOpen-headingOne_{{ artist.user.lastname }}">
			<div
				class="accordion-body">
				{{ include('component/_carousel.html.twig') }}
			</div>
		</div>
	</div>


	{# 	<div class="accordion-item">
			<h2 class="accordion-header" id="panelsStayOpen_{{ artist.user.lastname }}">
				<button
					class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo_{{ artist.user.lastname }}" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo_{{ artist.user.lastname }}">
	                titre
				</button>
			</h2>
			<div id="panelsStayOpen-collapseTwo_{{ artist.user.lastname }}" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen_{{ artist.user.lastname }}">
				<div
					class="accordion-body">contenu 
				</div>
			</div>
		</div> #}


	<div class="accordion-item">
		<h2 class="accordion-header" id="panelsStayOpen_{{ artist.user.lastname }}">
			<button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseThree_{{ artist.user.lastname }}" aria-expanded="false" aria-controls="panelsStayOpen-collapseThree_{{ artist.user.lastname }}">
				À propos de
				{{artist.user.lastname }}
			</button>
		</h2>
		<div id="panelsStayOpen-collapseThree_{{ artist.user.lastname }}" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen_{{ artist.user.lastname }}">
			<div class="accordion-body">
				{{ artist.aboutMe }}
			</div>
		</div>
	</div>
</div>

templates/component/_carousel.html.twig
<div id="carouselExampleCaptions_{{ artist.user.lastname }}" class="carousel slide" data-bs-ride="false">

	<div class="carousel-indicators">
		{% for artwork in artist.artworks|slice(0, 3) %}
			<button type="button" data-bs-target="#carouselExampleCaptions_{{ artist.user.lastname }}" data-bs-slide-to="{{loop.index0}}" class="{{ loop.first ? 'active' : '' }}" aria-current="true" aria-label="Slide {{loop.index}}"></button>
		{% endfor %}
	</div>

	<div class="carousel-inner">
		{% for artwork in artist.artworks|slice(0, 3) %}

			
			<div class="carousel-item {{ loop.first ? 'active' : '' }}">
				<img src="{{ artwork.artwork is null ? "https://picsum.photos/id/" ~ random(1, 200) ~ "/300/200": vich_uploader_asset(artwork) }}" class="d-block w-100" alt="Une oeuvre de {{ artist.user.lastname }}">
				<div class="carousel-caption d-none d-md-block">
					<h5 class="text-truncate" >{{ artwork.name }}</h5>
					<p class="text-truncate">{{ artwork.tool }}</p>
				</div>
			</div>

		{% endfor %}
	</div>
	<button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions_{{ artist.user.lastname }}" data-bs-slide="prev">
		<span class="carousel-control-prev-icon" aria-hidden="true"></span>
		<span class="visually-hidden">Précédent</span>
	</button>
	<button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions_{{ artist.user.lastname }}" data-bs-slide="next">
		<span class="carousel-control-next-icon" aria-hidden="true"></span>
		<span class="visually-hidden">Suivant</span>
	</button>
</div>

templates/component/_categories.html.twig
{% for category in categories %}
	<li>
		<a class="dropdown-item d-flex align-items-center" href="{{ path('app_inspiration_category', { 'id': category.id }) }}"><i class="bi bi-tag me-3"></i>{{ category.name }}</a>
	</li>
{% endfor %}

templates/component/_chat.html.twig
<div class="container">
	<div class="row clearfix">
		<div class="col-lg-12">
			<div class="card chat-app">

				<div id="plist" class="people-list">
					<ul class="list-unstyled chat-list mt-2">
						{% for tchatter in tchatters %}

							<li class="d-flex flex-column align-items-start">
								<a href="{{ path('app_artist_show_one_artist', { 'id': tchatter.user.id }) }}">
									<img class="avatarNavbar  border mb-2" src="{{ tchatter.user.avatar is empty ? asset ( 'build/images/default_avatar.gif') : vich_uploader_asset(tchatter.user) }}" alt="avatar">
									<div class="about ">
										<div class="name">{{ tchatter.user.lastname }}</div>
																		</div>
								</a>
							</li>
						{% endfor %}

					</ul>
				</div>



				<div class="chat">
					<div class="chat-header ">
						<div class="row clearfix ">

							<div class="d-flex flex-column justify-content-center align-content-center  ">
								<a href="{{ path('app_artist_show_one_artist', { 'id': artwork.artist.user.id }) }}">
									<img class="avatarNavbar  border" src="{{ artwork.artist.user.avatar is empty ? asset ( 'build/images/default_avatar.gif') : vich_uploader_asset(artwork.artist.user) }}" alt="avatar">
								</a>
								<div class="chat-about">
									<h6 class="m-b-0">{{ artwork.artist.user.lastname }}</h6>
									<small class="about-me text-truncate">{{ artwork.artist.aboutMe }}</small>
								</div>
							</div>


						</div>
					</div>
					<div class="chat-history ">
						<ul class="m-b-0">

							{% for comment in comments %}
								<div class="row {{ comment.author == artwork.artist ? '' : 'justify-content-end' }}">

									<div class="d-flex flex-column col-12 col-lg-6 ">
										<h6 class="m-b-0">{{ comment.author.user.lastname }}</h6>
										<div class="message-data d-flex align-items-center ">
											<img class="avatarNavbar  border" src="{{ comment.author.user.avatar is empty ? asset ( 'build/images/default_avatar.gif') : vich_uploader_asset(comment.author.user) }}" alt="avatar">
											<span class="message-data-time">{{ comment.creationDate|format_datetime(locale='fr') }}</span>
										</div>
										<p class="message other-message ">
											{{ comment.comment|nl2br }}
										</p>
									</div>

								</div>
							{% endfor %}
						</ul>
					</div>


				</div>
					<div class="chat-message clearfix">
						<div class="input-group mb-0 d-flex" >

							{% include "comment/_form.html.twig" %}
						</div>
					</div>
			</div>
		</div>
	</div>
</div>

templates/component/_footer.html.twig
{% block footer %}

	<footer class="mt-5 bg-dark ">
		<div class="container ">
			<div class="row justify-content-center">
				<div class="col-sm-8">


					<dl class="d-flex justify-content-around mt-5">
						<dd>
							<a href="#" >
								<i class="fs-1 bi bi-facebook"></i>
							</a>
						</dd>

						<dd>
							<a href="#">
								<i class="fs-1 bi bi-twitter"></i>
							</a>
						</dd>

						<dd>
							<a href="#">
								<i class="fs-1 bi bi-snapchat"></i>
							</a>
						</dd>

						<dd>
							<a href="#">
								<i class="fs-1 bi bi-instagram"></i>
							</a>
						</dd>


					</dl>
					<ul class="d-flex justify-content-center p-0 m-0">
						<li class="list-inline-item ">
							<a class="text-decoration-none d-flex flex-column align-items-center" href="{{ path('app_index') }}"><i class="fs-3 bi bi-house mb-1 mt-5"></i>- Accueil</a>
						</li>
						<li class="list-inline-item">
							<a class="text-decoration-none d-flex flex-column align-items-center" href="#"><i class="fs-3 bi bi-map mb-1 mt-5"></i>- Plan</a>
						</li>
						<li class="list-inline-item">
							<a class="text-decoration-none d-flex flex-column align-items-center" href="#"><i class="fs-3 bi bi-palette2 mb-1 mt-5"></i>- About </a>
						</li>
						<li class="list-inline-item">
							<a class="text-decoration-none d-flex flex-column align-items-center" href="#"><i class="fs-3 bi bi-radioactive mb-1 mt-5"></i>- Mentions -</a>
						</li>
					</ul>
				</div>
				<div class="d-flex justify-content-center">
					<a class="text-decoration-none fs-3 text-center mt-3 pb-3">Dessine moi un mouton - 2023</a>
				</div>
			</div>
		</div>

	</footer>
{% endblock %}

templates/component/_navbar.html.twig
<nav class="navbar navbar-dark bg-dark fixed-top">
	<div class="container-fluid">
		<a class="navbar-brand d-flex align-items-center" href="{{ path('app_index') }}">
			<i class="bi bi-easel2 mx-2 fs-1"></i>Dessine moi un mouton</a>
		<button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
			<div class="d-flex justify-content-end">
				<button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
			</div>
			<div class="offcanvas-header">
				<h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">
					{% if app.user %}
						<div class="fs-2">

							<img class="rounded-circle border mb-2 avatarNavbar " src="{{ app.user.avatar is empty ? asset ( 'build/images/default_avatar.gif') : vich_uploader_asset(app.user) }}" alt="Image de profil" id="avatar">
							{{ app.user.lastname }}

						</div>
						<a class="nav-link active mb-5 d-flex align-items-center" aria-current="page" href="{{ path('app_logout') }}">
							<i class="bi bi-box-arrow-in-left me-3"></i>Déconnexion</a>
						<a class="nav-link mt-3  d-flex align-items-center" href="{{ path('app_index') }}">
							<i class="bi bi-house me-3"></i>Accueil</a>

						<div class="d-flex flex-column">
							{% if is_granted('ROLE_ARTIST') %}
								<a href="{{ path('app_artist_edit') }}" class="me-5 text-decoration-none fs-5 d-flex align-items-center">
									<i class="bi bi-person-gear me-3"></i>
									<small>Mon profil</small>
								</a>
								<a href="{{ path('app_artwork_index') }}" class="me-5 text-decoration-none fs-5 d-flex align-items-center">
									<i class="bi bi-easel2  me-3"></i>
									<small>Mes œuvres</small>
								</a>
								<a href="{{ path('app_artwork_favories') }}" class="me-5 text-decoration-none fs-5 d-flex align-items-center">
									<i class="bi bi-palette me-3"></i>
									<small>Mes favoris</small>
								</a>
							{% endif %}


							{% if is_granted('ROLE_ADMIN')%}

								<p class="dropdown-item text-decoration-none pt-5 m-0 d-flex align-items-center">
									<i class="bi bi-gear me-3"></i>Administrer</p>
								<a href="{{ path('app_category_index') }}" class="me-5 text-decoration-none fs-5  d-flex align-items-center">
									<i class="bi bi-tags me-3"></i>
									<small>Catégories</small>
								</a>
								<a href="{{ path('app_user_index') }}" class="me-5 text-decoration-none fs-5 d-flex align-items-center">
									<i class="bi bi-people me-3"></i>
									<small>Utilisateurs</small>
								</a>
								<a href="{{ path('app_comment_index') }}" class="me-5 text-decoration-none fs-5 d-flex align-items-center">
									<i class="bi bi-chat-left-quote me-3"></i>
									<small>Commentaires</small>
								</a>

							{% endif %}


						</div>


					{% else %}
						Menu
					{% endif %}

				</h5>
			</div>

			<div class="offcanvas-body">
				<ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
					<li class="nav-item">

						{% if not app.user %}
							<a class="nav-link active  d-flex align-items-center" aria-current="page" href="{{ path('app_login') }}">
								<i class="bi bi-box-arrow-in-right me-3"></i>Connexion</a>
						{% endif %}
					</li>

					{# 					<form class="d-flex mt-3" role="search">
																																				<input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
																																				<button class="btn btn-success" type="submit">Rechercher</button>
																																			</form> #}
					<hr class="dropdown-divider">
					<p class="dropdown-item text-decoration-none fs-5 m-0 pt-5 d-flex align-items-center">
						<i class="bi bi-tags me-3"></i>Catégories</p>
					<li class="nav-item dropdown">{{ render(controller('App\\Controller\\CategoryController::categories')) }}
					</li>
					<li>
						<a class="dropdown-item d-flex align-items-center" href="{{ path('app_artist_all') }}"><i class="bi bi-people me-3"></i>Artistes</a>
					</li>

				</li>
			</ul>
		</div>
	</div>
</div></nav>